name: 'Zola Buikd'
description: 'Build a Zola site for deployment'
author: 'Cory Alder'

inputs:

  directory:
    description: 'Zola directory'
    default: .
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'zap'  
  color: 'green'
